version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      traefik.enable: true
      traefik.http.routers.web-main.rule: "Host(`stevenmcsorley.co.uk`)"
      traefik.http.routers.web-main.entrypoints: web
      traefik.http.routers.web-main.service: "web-main"
      traefik.http.services.web-main.loadbalancer.server.port: "8000"

    networks:
      - proxy

networks:
  proxy:
    external: true
