version: "3.9"

services:
  traefik:
    image: traefik:v2.0
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8087:8080"
    command:
      - --api.insecure=false
      - --api.dashboard=false
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/dynamic.yml
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic.yml:/dynamic.yml
    networks:
      - proxy

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`${WEB_HOST}`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web-secure.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=8000"
    networks:
      - proxy
      - backend

  kafka:
    image: bitnami/kafka:latest
    healthcheck:
      test:
        [
          "CMD",
          "kafka-broker-api-versions",
          "--bootstrap-server=localhost:9092",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - backend
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    networks:
      - backend
    depends_on:
      - kafka
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${BACKEND_HOST}`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      # - "traefik.enable=true"
      # - "traefik.http.routers.backend.rule=Host(`backend.${WEB_HOST}`)"
      # - "traefik.http.routers.backend.entrypoints=websecure"
      # - "traefik.http.routers.backend.tls=true"
      # - "traefik.http.services.backend.loadbalancer.server.port=8080"

  data-simulator:
    build:
      context: ./data-simulator
    depends_on:
      - kafka
    networks:
      - backend

  kafka-tools:
    image: bitnami/kafka:latest
    networks:
      - backend
    entrypoint: ["tail", "-f", "/dev/null"]

  bdd-tests:
    build:
      context: ./bdd-tests
      dockerfile: Dockerfile.bdd
    command: npm run test
    volumes:
      - ./bdd-tests:/bdd-tests
    networks:
      - backend

networks:
  proxy:
    external: true
  backend:
    external: true
