version: "3.9"

services:
  traefik:
    image: traefik:v2.8.1
    restart: always
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8087:8080"
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/dynamic.yml
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dynamic.yml:/dynamic.yml
    networks:
      - proxy

networks:
  proxy:
    name: "proxy"
