global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "backend"
    static_configs:
      - targets: ["backend-server:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
