name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: stevenmcsorley72/ohm-web:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "Navigating to project directory..."
            cd ${{ secrets.VPS_PATH }}

            echo "Backing up .env file..."
            cp .env .env.backup

            echo "Stashing local changes..."
            git stash

            echo "Pulling latest changes from Git..."
            git pull origin main || (git stash pop && exit 1)

            echo "Applying stashed changes..."
            git stash pop

            echo "Restoring .env file..."
            mv .env.backup .env

            echo "Pulling the latest Docker images..."
            docker-compose pull

            echo "Rebuilding and restarting Docker containers..."
            docker-compose down
            docker-compose up --build -d

            echo "Displaying running Docker containers..."
            docker ps
            echo "Inspecting Docker container..."
            docker inspect $(docker ps -q)

            echo "Cleaning up Docker system..."
            docker system prune -f
            docker image prune -f
