# Use an official Node.js runtime as a parent image
FROM mcr.microsoft.com/playwright:focal

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of your application code to the working directory
COPY . .

# Install Playwright dependencies
RUN npx playwright install --with-deps

# Expose a port if necessary (not usually required for testing)
# EXPOSE 8000

# Command to run BDD tests
CMD ["npm", "run", "bdd"]
